### PR TITLE
Vue Support with Vue-Loader 15 / Mini CSS Extract Plugin

### PR DESCRIPTION
**Pull request by lukepolo**
Hoping I can help you finish this up, if this is not helpful let me know~

### CODE REVIEW

**Comment by thecrypticace** [comment]
Oh wow this is super helpful! I need to rebase my feature/webpack-4 branch so all these intermediate commits should hopefully disappear. I'll make sure to do that today.

**Comment by lukepolo** [comment]
Well , not all of its working sadly, im having some issues with the vue-loader , and not really sure why

**Comment by thecrypticace** [comment]
Ah yeah we can work through that. I encountered some oddities regarding some things. But hey this is a really big help. Thanks for picking this up for me!

**Comment by lukepolo** [comment]
So reading more into whats going on, it would seem we now need to attach the `vue-loader` to the css component rather than handling it with the vue-loader options.  Which means we need to re-think how we should inject vue-loader into the css component. 

Not 100% sure , but thats what I believe is happening and why things fail.

**Comment by thecrypticace** [comment]
Yeah, the vue-loader's loader needs to be attached to the CSS loader. One way of doing this is probably looping over the registered rules and fining the CSS ones and pushing the cue-loader onto the stack of loaders for the relevant rules.

**Comment by lukepolo** [comment]
Currently Vue still fails with these rules applied : 

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACANnGqBuBXOAJT0wGdUBeVYVAJxLlKVQB0pUPOBta1eUmMwD0LFgDoAFjAC26ACRCANBggBDACZxaTVDwDkU2QFp0azbT2oAuqgC+itpye9+g1EIAUosR4AOUAHMAHwArXzgAfmCAgEsAMwBKOSCAPQ8PCIBCOOgYBLEEgCpvUhwAuQSlR2cnUw0tHWqa7l4682Y9OJjMEzMtPQd2ZuaIXxgY6B0aKFVpOGVfPAAjdBiwAAVVGAkOoUtbO0Hh5xo2rQ6Y6QDe+osj4+dR8cnmGgRVFbh1Zhh6edRYnFSGtMK97KhpBAAF5hOABMHKJ4xfzw6jg0oBCBguw4mz2JonPiMNyebweADuEDicQATBEgjAYHEgnAIDAgmzEskcrAxMVxBiKlUhsMzrQOl0emKBgSakiXrwZnMFstVhstjtUHo9jj8SLCa5hGSwHhaEFVFAYklhQ8xRLunAbuYZfq5WMJlApqglXAOlwfVYxFw4AAPGBWCJcCSqUgSKwDVCLFZrTbbXb7Q6yzg0Q3ubwhUghiIKe7DUNgdB4TTCDxQCCaAD6kPUDFIQSWEHJWgbkGkvmgCBgpEqpeaeFIvtYrpqPFOfXFWqWHzg6Cd-VHD1Q8s9zCzDxoYFUYAkcAAIjFaHAwDAILQAJ4-P4bzccXyXidD3fTl+6X96BA4C6P77hC9atswcSqOgE7PsBzgwKotABFgXpLLQnYTtozD6AAfKgNIAKSWFYyh4AEqxxA+fB-Lq1jWLBm6+JWsQ7lOcFOPovwWqQOS0NIRgQEsIRXjARjvqJpBvnAGhAexHFalxnq8fx9CwJccAJjQ-boHekroBBUEwagJ7oOEWGoJB0FwLidEHAceIMTmxK7AAqphpBCJWADWcDaWsMSel5MRCAAwvWcBCKMCCkBAppgBF6CIaoOArkY0gxCGQiuEIXRhqajA5aoPlGKovi+EI76xbQ8UeTGH4eaQdVCKVvhiKQYCkKQsnDOOk57vJ2puQ0nl4D5flgAFpBBaF4WReEnpVfFnlJSlq7pZldaNs2rZCOllpGB1pBGKGXHXkYTFkQFQjqDEAiefOYgFt1IF2lqh1rnc-UjO6Co0Ka+nUQQygxXFcAALKlQZVnKJc-a0DAAAy846AAjLqDGEq9ej9gI73ShjbrPKxX3NDQIPVeDkOA-MJPDDEmiwB0OMwIdz3ARdLGNN+L6zrTL7bl6AS0PTUMTpm3NwWhGENMweBQJoXRQF8BM-szh3rMxAUdKoeA3lJuXrnzjEQLjnUAGoNB6HQAGxiAADGIKMABwZni4s-nOtwdJV6ApUY-0fWzDwC1+7Fk4tlO+I+QNG846Fsq57kjWNEBqpN01hZoc3RRHy20MlqXrUIm1wE2YFkBmeoeyoXtao1nWByrTgh7wUkTcC0DME7iK64sMAAMowHeoJaqGvgWpo6gJuT8UQ1H1O0Q5-VOQIRriIdJYkwOADycShw8s6oL12FavgjoCMPjr429DfSrZTe8Mff4X1K84JnoeNv7Z9-L0Sq95gKLgR4rCdU3hLVA5ZKzVjYgfLUQghraGTr5VO-lArBUzhFKKC1QZ5wLmtDKWViQ5QyjAfKHlILFRahVRgEdaqdRQkIeutUyptVZvRLeStd772OIfJ++gz5GBflfN+ygP63xEXXOqgcf7gOzEfCcJ89BCMbjfI618lFSLvm7Je3MV4km8GQUgYCHiQKrJOLgJEOFwC4TAnhj8FF-gEco9Rn9bjv0MdInR1c+F1yHq-NxojXHOlER4rRNkq6kz-vo8QZ8Sw13aKfAg0iIk1D0WvNqfjxzGOODvPetjhi8IcfwpJziJFiLUWUl+45PHhNsiARQIABbIFAIhdC5JNiXk9MgEAyUID03qT0gQyBLIwRAGhI8PkB7jwmoEZAvwgYgHUBAMAwzDLzBAJNLQMB1j5wCNIVQqzoYgALCGAAQvnMAkz+6zDgAjAKcBDmjNijAPuNJHnrPHtoLQ3SlxLGHtAAZb4AowAAOr022MgJ2dsGlvhNnAEF+dfDdKkphFKAzLwAEc8AXjgDs1QeyDlIBGesic6U5lPhAMCQImAACKeA2QPKJWshpCElhgvUBCpANIWX526AFAIYVpD7O6XWJWAzeoABUPikHebYWwQA

**Comment by thecrypticace** [comment]
Yep, this looks good. 🎉 

I'm going to see if I can't figure out a PR for the mini-css plugin. It seems a bit daunting at the moment.

**Comment by lukepolo** [comment]
Yah , I was going to try but did look pretty tricky

**Pull request merged**
